<a href="https://colab.research.google.com/github/lucasloch/metodos_numericos/blob/main/MN_Lista1_Lucas_Vitor_Loch_Pereira.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<p align="center">
  <img src="https://www.aedi.ufpa.br/biologia/images/M_images/BioDistan/UFPA-LOGO.png" alt="UFPA logo" width=100/>
</p>

<p align="center">
  <strong>Universidade Federal do Pará (UFPA) - Tucuruí, PA - Brasil</strong><br>
  <strong>Faculdade de Engenharia de Computação</strong>
</p>

---

# Lista 1 da Disciplina de **Métodos Numéricos para Engenharia**

---

> Docente: **Otávio Noura Teixeira**<br>
> Discente: **Lucas Vitor Loch Pereira**<br>
> Matrícula: **201833840013**<br>
> Data: **30/09/2022**



---
## Questão 1
Escreva um programa que leia uma matriz e calcule o determinante desta matriz.


In [1]:
import numpy as np
from copy import deepcopy

def matriz_menor(matriz, linha, coluna):
    matriz_copia = deepcopy(matriz)
    matriz_copia.remove(matriz[linha])
    for i in range(len(matriz_copia)):
        matriz_copia[i].pop(coluna) 
    return matriz_copia

def determinante(matriz):  # Este método resolve apenas matrizes quadradas
  for linha in matriz:  # Verifica se a matriz é quadrada
    if len(linha) != len(matriz):
      return 'Não é uma matriz quadrada.'

  if len(matriz[0]) == 2:  # Caso a matriz seja de ordem 2
    det = matriz[0][0] * matriz[1][1] - matriz[1][0] * matriz[0][1]
    return det
  
  det = 0  # Esse método faz uso da recursão, onde vai buscando o determinante de matrizes menores
  for i in range(len(matriz)):
    det += ((-1)**i) * matriz[0][i] * determinante(matriz_menor(matriz, 0, i))
  return det

In [2]:
matriz = [
    [1, 0, 6], 
    [0, 1, 4], 
    [3, 6, 2]
]
print('Matriz:')
print('\n'.join([''.join(['{:4}'.format(valor) for valor in linha]) for linha in matriz]))
print(f'Determinante da matriz: {determinante(matriz)}')
print(f'Determinante da matriz: {np.linalg.det(matriz)} (com método "numpy.linallg.det")')

Matriz:
   1   0   6
   0   1   4
   3   6   2
Determinante da matriz: -40
Determinante da matriz: -40.0 (com método "numpy.linallg.det")


---
## Questão 2
Use eliminação de Gauss para resolver **Ax = b**, onde

$$A =
 \begin{bmatrix}
  2 & 0 & -1 & 0 \\
  0 & 1 & 2 & 0 \\
  -1 & 2 & 0 & 1 \\
  0 & 0 & 1 & -2
 \end{bmatrix}
B =
 \begin{bmatrix}
  1 & 0 \\
  0 & 0 \\
  0 & 1 \\
  0 & 0
 \end{bmatrix}$$

In [3]:
import numpy as np

def metodo_gauss(A, b):
  n = len(b)
  x = np.zeros(n, dtype=object)

  for k in range(0, n-1):
    for i in range(k+1, n):
      ratio = A[i,k] / A[k,k]
      for j in range(k, n-1):
        A[i,j] -= ratio * A[k,j]
      b[i] -= ratio * b[k]
        
  x[n-1] = b[n-1] / A[n-1, n-1]
  for i in range(n-2, -1, -1):
    soma_j = 0
    for j in range(i+1, n):
      soma_j += A[i,j] * x[j]
    x[i] = (b[i] - soma_j) / A[i,i]

  return x

In [4]:
A = np.array([
    [2, 0, -1, 0], 
    [0, 1, 2, 0], 
    [-1, 2, 0, 1], 
    [0, 0, 1, -2]
], dtype='float')

b = np.array([
    [1, 0], 
    [0, 0], 
    [0, 1], 
    [0, 0]
], dtype='float')

x = metodo_gauss(A, b)
x = np.stack(x, axis=0)

print('Matriz A:\n', A)
print('\nMatriz B:\n', b)
print('\nRESULTADO ENCONTRADO:\nx =', x)
print('\nRESULTADO COM O MÉTODO "numpy.linalg.solve()":\nx =', np.linalg.solve(A, b))
print('\nCHECANDO RESULTADO: A{x} - b\n',np.dot(A, x) - b)

Matriz A:
 [[ 2.   0.  -1.   0. ]
 [ 0.   1.   2.   0. ]
 [ 0.   0.  -4.5  1. ]
 [ 0.   0.   0.  -2. ]]

Matriz B:
 [[1.         0.        ]
 [0.         0.        ]
 [0.5        1.        ]
 [0.11111111 0.22222222]]

RESULTADO ENCONTRADO:
x = [[ 0.4382716  -0.12345679]
 [ 0.24691358  0.49382716]
 [-0.12345679 -0.24691358]
 [-0.05555556 -0.11111111]]

RESULTADO COM O MÉTODO "numpy.linalg.solve()":
x = [[ 0.4382716  -0.12345679]
 [ 0.24691358  0.49382716]
 [-0.12345679 -0.24691358]
 [-0.05555556 -0.11111111]]

CHECANDO RESULTADO: A{x} - b
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


---
## Questão 3
Use eliminação de Gauss para resolver **Ax = b**, onde

$$A =
 \begin{bmatrix}
  0 & 0 & 2 & 1 & 2 \\
  0 & 1 & 0 & 2 & -1 \\
  1 & 2 & 0 & -2 & 0 \\
  0 & 0 & 0 & -1 & 1 \\
  0 & 1 & -1 & 1 & -1
 \end{bmatrix}
B =
 \begin{bmatrix}
  1 \\
  1 \\
  -4 \\
  -2 \\
  -1
 \end{bmatrix}$$

In [5]:
import numpy as np

def metodo_gauss2(A, B):
  Ab = np.column_stack((A, B))  # Cria a matriz ampliada
  n = len(Ab) # Número de variáveis que se deve encontrar
  
  # Obtém a forma triangular superior:
  for i in range(n):
      k = np.argmax(np.abs(Ab[i:,i])) # buscando o maior pivo
      if k > 0:
        Ab[i+k], Ab[i] = np.copy(Ab[i]), np.copy(Ab[i+k]) # Trocando linhas
      m = Ab[i,i:] / Ab[i,i] # Multiplicadores
      for j in range(i+1, n): # Reduzindo as linhas abaixo da linha i
        Ab[j,i:] -= Ab[j,i] * m
        Ab[j,:i] = 0.

  Ab_copia = Ab.copy()

  # Resolve o sistema triangular superior:
  for i in range(n-1, -1, -1):
    for j in range(n-1, i, -1):
      Ab[i,-1] -= Ab[i,j] * Ab[j,-1]
    Ab[i,-1] /= Ab[i,i] # Última coluna de A tem a solução
  
  return Ab[:,-1], Ab_copia

In [6]:
A = np.array([
    [0, 0, 2, 1, 2], 
    [0, 1, 0, 2, -1], 
    [1, 2, 0, -2, 0], 
    [0, 0, 0, -1, 1], 
    [0, 1, -1, 1, -1]
], dtype='float')

b = np.array([1, 1, -4, -2, -1], dtype='float')

A_copia = A.copy()
b_copia = b.copy()
x, Ab = metodo_gauss2(A_copia, b_copia)

print('Matriz A:\n', A)
print('\nMatriz B:\n', b)
print('\nMatriz Aumentada Ab na forma triangular:\n', Ab)
print('\nRESULTADO ENCONTRADO:\nx =', x)
print('\nRESULTADO COM O MÉTODO "numpy.linalg.solve()":\nx =', np.linalg.solve(A, b))
print('\nCHECANDO RESULTADO: A{x} - b\n',np.dot(A, x) - b)

Matriz A:
 [[ 0.  0.  2.  1.  2.]
 [ 0.  1.  0.  2. -1.]
 [ 1.  2.  0. -2.  0.]
 [ 0.  0.  0. -1.  1.]
 [ 0.  1. -1.  1. -1.]]

Matriz B:
 [ 1.  1. -4. -2. -1.]

Matriz Aumentada Ab na forma triangular:
 [[ 1.   2.   0.  -2.   0.  -4. ]
 [ 0.   1.   0.   2.  -1.   1. ]
 [ 0.   0.   2.   1.   2.   1. ]
 [ 0.   0.   0.  -1.   1.  -2. ]
 [ 0.   0.   0.   0.   0.5 -0.5]]

RESULTADO ENCONTRADO:
x = [ 2. -2.  1.  1. -1.]

RESULTADO COM O MÉTODO "numpy.linalg.solve()":
x = [ 2. -2.  1.  1. -1.]

CHECANDO RESULTADO: A{x} - b
 [0. 0. 0. 0. 0.]


---
## Questão 4
Faça a decomposição LU da seguinte matriz:

$$\begin{bmatrix}
  4 & -1 & 0 \\
  -1 & 4 & -1 \\
  0 & -1 & 4
 \end{bmatrix}$$

In [7]:
import numpy as np

def decomposicaoLU(A):  
  U = np.copy(A)
  n = np.shape(U)[0]
  L = np.eye(n)
  for j in np.arange(n-1):
    for i in np.arange(j+1,n):
      L[i,j] = U[i,j] / U[j,j]
      for k in np.arange(j+1,n):
        U[i,k] = U[i,k] - L[i,j] * U[j,k]
        U[i,j] = 0
  return L, U

In [8]:
A = np.array([
    [4, -1, 0], 
    [-1, 4, -1], 
    [0, -1, 4]
], dtype='float')

L, U = decomposicaoLU(A)

print('Matriz L:\n', L)
print('\nMatriz U:\n', U)

Matriz L:
 [[ 1.          0.          0.        ]
 [-0.25        1.          0.        ]
 [ 0.         -0.26666667  1.        ]]

Matriz U:
 [[ 4.         -1.          0.        ]
 [ 0.          3.75       -1.        ]
 [ 0.          0.          3.73333333]]


---
## Questão 5
Escreva um programa que resolva o seguinte sistema **Ax=b** usando decomposição LU, para um valor arbitrário de n:

$$A = 
\begin{bmatrix}
  1 & 1/2 & 1/3 & \cdots \\
  1/2 & 1/3 & 1/4 & \cdots \\
  1/3 & 1/4 & 1/5 & \cdots \\
  \vdots & \vdots & \vdots & \ddots
 \end{bmatrix}$$

\begin{align}
  b_i = \sum_{j=1}^{n} A_{ij}
\end{align}

In [9]:
import numpy as np

def cria_matrizes(n):
    A, b = [], []
    for i in range(n):
        linha = [1 / (1+i+j) for j in range(n)]
        A.append(linha)
        b.append(sum(linha))
    return np.array(A), np.array(b)


def decomposicaoLU(A):  
  U = np.copy(A)
  n = np.shape(U)[0]
  L = np.eye(n)
  for j in np.arange(n-1):
    for i in np.arange(j+1,n):
      L[i,j] = U[i,j] / U[j,j]
      for k in np.arange(j+1,n):
        U[i,k] = U[i,k] - L[i,j] * U[j,k]
        U[i,j] = 0
  return L, U


def resolucaoLyB(L, b):
  y = []
  for i in range(len(b)):
        y.append(b[i])
        for j in range(i):
            y[i] = y[i] - (L[i,j] * y[j])
        y[i] = y[i] / L[i,i]
  return y


def resolucaoUxY(U, y):
  x = np.zeros_like(y)
  for i in range(len(x),0,-1):
    x[i-1] = (y[i-1] - np.dot(U[i-1, i:], x[i:])) / U[i-1, i-1]
  return x


def resolucao(A, b):
    L, U = decomposicaoLU(A)
    y = resolucaoLyB(L, b)
    x = resolucaoUxY(U, y)
    return L, U, x

In [10]:
n = int(input('Informe a ordem da matriz quadrada: '))
A, b = cria_matrizes(n)
L, U, x = resolucao(A, b)

print('\nMatriz A:')
print(A)
print('\nMatriz b:')
print(b)
print('\nMatriz U:')
print(U)
print('\nMatriz L:')
print(L,'\n')
cont = 0
for valor in x:
  print(f'x{cont}: {valor}')
  cont += 1
print('\nCHECANDO RESULTADO: A{x} - b\n',np.dot(A, x) - b)

Informe a ordem da matriz quadrada: 4

Matriz A:
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]

Matriz b:
[2.08333333 1.28333333 0.95       0.75952381]

Matriz U:
[[1.00000000e+00 5.00000000e-01 3.33333333e-01 2.50000000e-01]
 [0.00000000e+00 8.33333333e-02 8.33333333e-02 7.50000000e-02]
 [0.00000000e+00 0.00000000e+00 5.55555556e-03 8.33333333e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.57142857e-04]]

Matriz L:
[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [0.33333333 1.         1.         0.        ]
 [0.25       0.9        1.5        1.        ]] 

x0: 0.9999999999999778
x1: 1.0000000000002485
x2: 0.999999999999402
x3: 1.0000000000003886

CHECANDO RESULTADO: A{x} - b
 [0. 0. 0. 0.]


---
## Questão 6
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  0 & 1 & 3 \\
  3 & -1 & 2 \\
  -2 & 2 & -4
 \end{bmatrix}$$

In [11]:
import numpy as np

def metodo_gaussjordan(A):
  A = np.array(A)
  m, n = A.shape
  I = np.eye(m)  # Cria a matriz identidade de A
  aum_A = np.c_[A, I]  # Matriz aumentada de A
  
  # Aplicando Gauss-Jordan
  j = 0
  for i in range(m-1):
    pivo = aum_A[i][j]
    if pivo == 0:
      # Evitando a divisão por zero
      tst = False
      for k in range(i+1,m):
        if aum_A[k][j] != 0:
          temp = aum_A[k].copy()
          aum_A[k] = aum_A[i].copy()
          aum_A[i] = temp.copy()
          tst = True 
          break
      if tst == False:
        raise Exception("None")
      else:
        pivo = aum_A[i][j]
    for k in range(i+1, m):
      valor = aum_A[k][j]
      multiplicador = valor / pivo
      aum_A[k] = aum_A[k] - multiplicador*aum_A[i]
    j += 1
        
  j = m-1
  for i in range(m-1,0,-1):
    pivo = aum_A[i][j]
    for k in range(i-1,-1,-1):
      valor = aum_A[k][j]
      multiplicador = valor / pivo
      aum_A[k] = aum_A[k] - multiplicador*aum_A[i]
    j -= 1

  for i in range(m):
    aum_A[i] /= aum_A[i][i]

  return aum_A[:,m:]

In [12]:
A = np.array([
    [0, 1, 3], 
    [3, -1, 2], 
    [-2, 2, -4]
], dtype='float')

inv = metodo_gaussjordan(A)
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 0.  1.  3.]
 [ 3. -1.  2.]
 [-2.  2. -4.]]

Matriz inversa usando Gauss Jordan:
 [[ 0.    0.5   0.25]
 [ 0.4   0.3   0.45]
 [ 0.2  -0.1  -0.15]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 0.    0.5   0.25]
 [ 0.4   0.3   0.45]
 [ 0.2  -0.1  -0.15]]


---
## Questão 7
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  2 & 4 & 3 \\
  0 & 6 & 5 \\
  0 & 0 & 2
 \end{bmatrix}$$

In [13]:
A = np.array([
    [2, 4, 3], 
    [0, 6, 5], 
    [0, 0, 2]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando o método de Gauss-Jordan:\n', inv)
print('\nMatriz inversa usando o método "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[2. 4. 3.]
 [0. 6. 5.]
 [0. 0. 2.]]

Matriz inversa usando o método de Gauss-Jordan:
 [[ 0.5        -0.33333333  0.08333333]
 [ 0.          0.16666667 -0.41666667]
 [ 0.          0.          0.5       ]]

Matriz inversa usando o método "numpy.linalg.inv":
 [[ 0.5        -0.33333333  0.08333333]
 [ 0.          0.16666667 -0.41666667]
 [ 0.          0.          0.5       ]]


---
## Questão 8
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  2 & 0 & 0 \\
  3 & 4 & 0 \\
  4 & 5 & 6
 \end{bmatrix}$$

In [14]:
A = np.array([
    [2, 0, 0], 
    [3, 4, 0], 
    [4, 5, 6]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[2. 0. 0.]
 [3. 4. 0.]
 [4. 5. 6.]]

Matriz inversa usando Gauss Jordan:
 [[ 0.5         0.          0.        ]
 [-0.375       0.25        0.        ]
 [-0.02083333 -0.20833333  0.16666667]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 0.5         0.          0.        ]
 [-0.375       0.25       -0.        ]
 [-0.02083333 -0.20833333  0.16666667]]


---
## Questão 9
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  1 & 1/2 & 1/4 & 1/8 \\
  0 & 1 & 1/3 & 1/9 \\
  0 & 0 & 1 & 1/4 \\
  0 & 0 & 0 & 1
 \end{bmatrix}$$

In [15]:
A = np.array([
    [1, 1/2, 1/4, 1/8], 
    [0,  1,  1/3, 1/9], 
    [0,  0,   1,  1/4], 
    [0,  0,   0,   1]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[1.         0.5        0.25       0.125     ]
 [0.         1.         0.33333333 0.11111111]
 [0.         0.         1.         0.25      ]
 [0.         0.         0.         1.        ]]

Matriz inversa usando Gauss Jordan:
 [[ 1.         -0.5        -0.08333333 -0.04861111]
 [ 0.          1.         -0.33333333 -0.02777778]
 [ 0.          0.          1.         -0.25      ]
 [ 0.          0.          0.          1.        ]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 1.         -0.5        -0.08333333 -0.04861111]
 [ 0.          1.         -0.33333333 -0.02777778]
 [ 0.          0.          1.         -0.25      ]
 [ 0.          0.          0.          1.        ]]


---
## Questão 10
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  1 & 2 & 4 \\
  1 & 3 & 9 \\
  1 & 4 & 16
 \end{bmatrix}$$

In [16]:
A = np.array([
    [1, 2, 4], 
    [1, 3, 9], 
    [1, 4, 16]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]

Matriz inversa usando Gauss Jordan:
 [[ 6.  -8.   3. ]
 [-3.5  6.  -2.5]
 [ 0.5 -1.   0.5]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 6.  -8.   3. ]
 [-3.5  6.  -2.5]
 [ 0.5 -1.   0.5]]


---
## Questão 11
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  4 & -1 & 0 \\
  -1 & 4 & -1 \\
  0 & -1 & -4
 \end{bmatrix}$$

In [17]:
A = np.array([
    [4, -1, 0], 
    [-1, 4, -1], 
    [0, -1, -4]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 4. -1.  0.]
 [-1.  4. -1.]
 [ 0. -1. -4.]]

Matriz inversa usando Gauss Jordan:
 [[ 0.265625  0.0625   -0.015625]
 [ 0.0625    0.25     -0.0625  ]
 [-0.015625 -0.0625   -0.234375]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 0.265625  0.0625   -0.015625]
 [ 0.0625    0.25     -0.0625  ]
 [-0.015625 -0.0625   -0.234375]]


---
## Questão 12
Inverta a seguinte matriz utilizando o método Gauss-Jordan:

$$\begin{bmatrix}
  4 & -2 & 1 \\
  -2 & 1 & -1 \\
  1 & -2 & 4
 \end{bmatrix}$$

In [18]:
A = np.array([
    [4, -2, 1], 
    [-2, 1, -1], 
    [1, -2, 4]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 4. -2.  1.]
 [-2.  1. -1.]
 [ 1. -2.  4.]]

Matriz inversa usando Gauss Jordan:
 [[-0.66666667 -2.         -0.33333333]
 [-2.33333333 -5.         -0.66666667]
 [-1.         -2.         -0.        ]]

Matriz inversa usando "numpy.linalg.inv":
 [[-0.66666667 -2.         -0.33333333]
 [-2.33333333 -5.         -0.66666667]
 [-1.         -2.         -0.        ]]


---
## Questão 13
Inverta a seguinte matriz utilizando qualquer método:

$$\begin{bmatrix}
  5 & -3 & -1 & 0 \\
  -2 & 1 & 1 & 1 \\
  3 & -5 & 1 & 2 \\
  0 & 8 & -4 & -3
 \end{bmatrix}$$

In [19]:
A = np.array([
    [5, -3, -1, 0], 
    [-2, 1, 1, 1], 
    [3, -5, 1, 2], 
    [0, 8, -4, -3]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 5. -3. -1.  0.]
 [-2.  1.  1.  1.]
 [ 3. -5.  1.  2.]
 [ 0.  8. -4. -3.]]

Matriz inversa usando Gauss Jordan:
 [[ 1.125   1.     -0.875  -0.25  ]
 [ 0.8125  1.     -0.6875 -0.125 ]
 [ 2.1875  2.     -2.3125 -0.875 ]
 [-0.75    0.      1.25    0.5   ]]

Matriz inversa usando "numpy.linalg.inv":
 [[ 1.12500000e+00  1.00000000e+00 -8.75000000e-01 -2.50000000e-01]
 [ 8.12500000e-01  1.00000000e+00 -6.87500000e-01 -1.25000000e-01]
 [ 2.18750000e+00  2.00000000e+00 -2.31250000e+00 -8.75000000e-01]
 [-7.50000000e-01 -5.55111512e-16  1.25000000e+00  5.00000000e-01]]


---
## Questão 14
Inverta a seguinte matriz utilizando qualquer método:

$$\begin{bmatrix}
  4 & -1 & 0 & 0 \\
  -1 & 4 & -1 & 0 \\
  0 & -1 & 4 & -1 \\
  0 & 0 & -1 & 4
 \end{bmatrix}$$

In [20]:
A = np.array([
    [4, -1, 0, 0], 
    [-1, 4, -1, 0], 
    [0, -1, 4, -1], 
    [0, 0, -1, 4]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  4.]]

Matriz inversa usando Gauss Jordan:
 [[0.26794258 0.07177033 0.01913876 0.00478469]
 [0.07177033 0.28708134 0.07655502 0.01913876]
 [0.01913876 0.07655502 0.28708134 0.07177033]
 [0.00478469 0.01913876 0.07177033 0.26794258]]

Matriz inversa usando "numpy.linalg.inv":
 [[0.26794258 0.07177033 0.01913876 0.00478469]
 [0.07177033 0.28708134 0.07655502 0.01913876]
 [0.01913876 0.07655502 0.28708134 0.07177033]
 [0.00478469 0.01913876 0.07177033 0.26794258]]


---
## Questão 15
Inverta a seguinte matriz utilizando qualquer método:

$$\begin{bmatrix}
  1 & 3 & -9 & 6 & 4 \\
  2 & -1 & 6 & 7 & 1 \\
  3 & 2 & -3 & 15 & 5 \\
  8 & -1 & 1 & 4 & 2 \\
  11 & 1 & -2 & 18 & 7
 \end{bmatrix}$$

In [21]:
A = np.array([
    [1, 3, -9, 6, 4], 
    [2, -1, 6, 7, 1], 
    [3, 2, -3, 15, 5], 
    [8, -1, 1, 4, 2], 
    [11, 1, -2, 18, 7]
], dtype='float')

inv = metodo_gaussjordan(A)  # Função criada na questão 6
print('Matriz Original:\n', A)
print('\nMatriz inversa usando Gauss Jordan:\n', inv)
print('\nMatriz inversa usando "numpy.linalg.inv":\n', np.linalg.inv(A))

Matriz Original:
 [[ 1.  3. -9.  6.  4.]
 [ 2. -1.  6.  7.  1.]
 [ 3.  2. -3. 15.  5.]
 [ 8. -1.  1.  4.  2.]
 [11.  1. -2. 18.  7.]]

Matriz inversa usando Gauss Jordan:
 [[-4.63853894e+13 -4.63853894e+13 -4.63853894e+13 -9.27707788e+13
   9.27707788e+13]
 [-2.20330600e+14 -2.20330600e+14 -2.20330600e+14 -4.40661199e+14
   4.40661199e+14]
 [-3.68974689e+13 -3.68974689e+13 -3.68974689e+13 -7.37949377e+13
   7.37949377e+13]
 [-5.00000000e-01 -5.00000000e-01  5.00000000e-01  0.00000000e+00
   0.00000000e+00]
 [ 9.38249922e+13  9.38249922e+13  9.38249922e+13  1.87649984e+14
  -1.87649984e+14]]

Matriz inversa usando "numpy.linalg.inv":
 [[-2.22649869e+15 -2.22649869e+15 -2.22649869e+15 -4.45299738e+15
   4.45299738e+15]
 [-1.05758688e+16 -1.05758688e+16 -1.05758688e+16 -2.11517376e+16
   2.11517376e+16]
 [-1.77107851e+15 -1.77107851e+15 -1.77107851e+15 -3.54215701e+15
   3.54215701e+15]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 4.50359963e+15 

---
## Questão 16
Encontre a menor raiz positiva e real de “$x^{3} − 3.23x^{2} − 5.54x + 9.84 = 0$” utilizando o método da bisecção.

In [22]:
def metodo_bissecao(f, a, b, erro, qtd_iter):  
  fa = f(a)
  while qtd_iter > 0:
    p = (a + b)/2  # Ponto da bissecao
    fp = f(p)

    # Condicao de parada
    if ((fp == 0) or ((b-a)/2 < erro)):  
      return p, qtd_iter

    # Define o intervalo
    if (fa * fp > 0):
      a = p
      fa = fp
    else:
      b = p
    qtd_iter -= 1
  return p, qtd_iter

In [23]:
f = lambda x: x**3 - 3.23*x**2 + 5.54*x + 9.84
raiz, iteracoes = metodo_bissecao(f, -5, 5, 1e-8, 1000)
print('Raiz encontrada:', raiz)
print('Numero de iteracoes:', iteracoes)

Raiz encontrada: -1.004657642915845
Numero de iteracoes: 971


---
## Questão 17
 A menor raiz maior que zero de “$cosh(x) cos(x−1) = 0$” reside no intervalo (4, 5). Crie um programa que encontre a raiz com 6 casas decimais de precisão.

In [24]:
import numpy as np

def raiz_ridder(f, a, b, tolerancia, qtd_iter):  
  fa = f(a)
  fb = f(b)
  ultimoX = 0
  while qtd_iter > 0:
    # Reparte o ponto
    p = (a + b)/2
    fp = f(p)
    # Aplica a fórmula de aproximação | será positivo se f(a)−f(b)>0  e negativo se f(a)−f(b)<0
    try:
      aprox = (p-a) * fp / np.sqrt(fp**2 - fa*fb)
    except ZeroDivisionError:
      return None, qtd_iter
    aprox = -aprox if (fa - fb) < 0 else aprox

    # Condicao de parada
    x = p + aprox
    fx = f(x)

    # Na primeira iteração acontece: SE x for menor que a tolerância, encontrou!
    if abs(x - ultimoX) < tolerancia*(1 if abs(x) < 1 else abs(x)):
      return p, qtd_iter
    ultimoX = x

    # Ajusta o intervalo
    if fx*fp > 0.0:
      if fa*fx > 0.0:
        a = x
        fa = fx
      else:
        b = x
        fb = fx
    else:
      a = p
      b = x
      fa = fp
      fb = fx
    qtd_iter -= 1
  return p, qtd_iter

In [25]:
f = lambda x: np.cosh(x) * np.cos(x) - 1
raiz, iters = raiz_ridder(f, 4, 5, 1e-6, 1000)
print('Raíz encontrada:', raiz)
print('Número de iterações:', iters)

Raíz encontrada: 4.702214518015284
Número de iterações: 997


---
## Questão 18
Determine as duas raízes de “$sen(x+3) cos(x−2) = 0$” do intervalo (−2, 2), utilizando o método de Newton Raphson.


In [26]:
import numpy as np

# Método de Newton-Raphson
def metodo_newtonraphson(x):
  h = f(x) / df(x)
  while abs(h) >= 0.00001:  # Tolerância
    h = f(x) / df(x)
    x = x - h
  return x

# Equação
f = lambda x: np.sin(x+3) * np.cos(x-2)

# Derivada da equação
df = lambda x: np.cos(2*x+1)

# Intervalo
x1 = -2
x2 = 2
print(f'Raíz para {x1}: {metodo_newtonraphson(x1)}')
print(f'Raíz para {x2}: {metodo_newtonraphson(x2)}')

Raíz para -2: -2.7123889803846897
Raíz para 2: 6.712388980394433


---
## Questão 19
Determine as coordenadas dos dois pontos onde os círculos $(x - 2)^2 + y^2 = 4$ e $x^2 + (y - 3)^2 = 4$ se cruzam. Comece estimando as localizações dos pontos a partir de um esboço dos círculos e, em seguida, use o método Newton-Raphson para calcular as coordenadas.


---
## Questão 20
<img align='right' src='https://lh3.googleusercontent.com/drive-viewer/AJc5JmTCWsqK4GY6s9a3AoWyGiOPsrpcS-FI4WYHT10sXHiM2KH9Xyo0alyU0ozS8L_tLLqIgcVFVbs=w1366-h657' style='vertical-align:top'>


O tanque de óleo cilíndrico de raio r e comprimento L é enchido até a profundidade h. O volume de óleo no tanque é

\begin{align}
  V = r^{2}L \left[\phi - \left(1 - \frac hr\right) \sin\phi \right]
\end{align}

Onde

\begin{align}
  \phi = \cos^{-1} \left(1 - \frac hr \right)
\end{align}

Se o tanque estiver 3/4 cheio, determine *h/r*.